VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :mongodb_client do |mongodb_client|
    mongodb_client.vbguest.auto_update = true
    mongodb_client.vbguest.no_remote = true
    mongodb_client.vm.box = "ubuntuBox"
    mongodb_client.vm.network :private_network, ip: "192.168.33.10"

    mongodb_client.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--memory", "512"]
    end

    mongodb_client.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "init_client.pp"
    end
  end

  config.vm.define :mongodb_01 do |mongodb_01|
    mongodb_01.vm.box = "ubuntuBox"
    mongodb_01.vm.network :private_network, ip: "192.168.33.11"

    mongodb_01.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--memory", "512"]
    end

    mongodb_01.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "init_mongodb.pp"
    end
  end
end
